name: Push
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Docker Build & Push'
        run: |
          make docker-push
